print("what is your favorite animal?")
animal = input("Stingray")
print("What is a fun fact about them?")
funfact = input("They Have a barb on their tail")
print("What do they eat")
food = input("shimp")
print("What color are they?")
color = input("Light gray")
print("How do they move?")
user_input = input("swiming through the water")
print("Your favorite animal is the " + animal + "a fun fact about them is " + funfact + ". They eat " + food + "and they are " + color + "in color. They move by " + user_input)
