print("what is your favorite animal?")
animal = input("")
print("What is a fun fact about them?")
funfact = input("")
print("What do they eat")
food = input("")
print("What color are they?")
color = input("")
print("How do they move?")
user_input = input("")
print("where do they live?")
live = input("")
print("")
print("Your favorite animal is a " + animal + ". A fun fact about them is " + funfact + ". They eat " + food + " and they are " + color + " in color. They move by " + user_input)
