print("what is your favorite animal?")
user_input = input("Stingray")
print("What is a fun fact about them?")
user_input2 = input("They Have a barb on their tail")
print("What do they eat")
user_input3 = input("shimp")
print("What color are they?")
user_input4 = input("Light gray")
print("How do they move?")
user_input5 = input("swiming through the water")
print("Your favorite animal is the " + user_input + "a fun fact about them is " + user_input2 + ". They eat " + user_input3 + "and they are " + user_input4 + "in color. They move by " + user_input5 )
