ans_1 = int(input("Give me a whole number that is greater then 17.\n"))
print(ans_1 > 17)
ans_2 = float(input("Give me a decimal number that is less then 1.2\n"))
print(ans_2 < 1.2)
ans_3 = int(input("Give me a whole number that is grater then or equal to 57.\n"))
print(ans_3 >= 57) 
ans_4 = int(input("GIve me a whole number less then 15 and greater than or equal to 12\n"))
print(ans_4 < 15 and ans_4 >= 12)
ans_5 = int(input("Give me a whole number that is equalto 5.\n"))
print(ans_5 == 5)
ans_6 = int(input("Give me a number that is less then 24 or greater then 36\n"))
print(ans_6 < 24 or ans_6 > 36 )
ans_7 = int(input("Give me a number that is not less then 247\n"))
print(ans_7 >= 247 )