# Ask for a name then item, verb, another verb, a person, place, vehicle, animal and lastly a object
#Print out the completed story

print ("Give me a name.")
name1 = input ("")
print ("Give me a item.")
noun1 = input("")
print ("Give me a verb.")
verb1 = input("")
print ("Give me a diffrent verb.")
verb2 = input("")
print ("Give me a person.")
person1 = input("")
print ("Give me a place.")
place1 = input("")
print ("Give me a vehicle.")
vehicle = input ("")
print ("Give me an animal.")
animal = input("")
print ("Give me a large object")
object = input ("")
print ("One day " + name1 + " decided to take their " + noun1 + " for a " + verb1 + ". " + name1 + " got up and " + verb2 + " down the stairs. Then " + name1 + " whent to the closet to grab the " + noun1 + " then " + name1 + " decided to go meet " + person1 + " at " + place1 + " so " + name1 + " hopped in " + vehicle + ". Then all of a sudden a " + animal + " was infront of " + name1 + "! " + name1 +" swerved out to the way and ended up hitting a " + object + ". " + name1 + " died.")
